feign:
  conveyor:
    url: http://localhost:8080/conveyor
server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/deal
    username: user
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
              spring:
                json:
                  add:
                    type:
                      headers: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/deal
    user: user
topic:
  finish-registration: finish-registration
  create-documents: create-documents
  send-documents: send-documents
  send-ses: send-ses
  credit-issued: credit-issued
  application-denied: application-denied

---
spring:
  profiles:
    active: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/deal
  kafka:
    producer:
      bootstrap-servers: kafka1:9092
  liquibase:
    url: jdbc:postgresql://postgres:5432/deal
feign:
  conveyor:
    url: http://conveyor:8080/conveyor


