feign:
  conveyor:
    url: http://localhost:8080/conveyor
server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/deal
    username: user
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      bootstrap-servers: /localhost:9092
#      group-id: dossier
#      auto-offset-reset: earliest
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#          json:
#            value:
#              default:
#                type: org.openapitools.model.EmailMessage
#          deserializer:
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JsonDeserializer
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#      properties:
#        spring:
#          json:
#            value:
#              default:
#                type: org.openapitools.model.EmailMessage
#          serializer:
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/deal
    user: user
topic:
  finish-registration: finish-registration
  create-documents: create-documents
  send-documents: send-documents
  send-ses: send-ses
  credit-issued: credit-issued
  application-denied: application-denied




