version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "deal"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "finish-registration,create-documents,send-documents,send-ses,credit-issued,application-denied"

  application:
    build: ./application
    container_name: application
    restart: always
    ports:
      - "8082:8082"

  conveyor:
    build: ./conveyor
    container_name: conveyor
    restart: always
    ports:
      - "8080:8080"

  dossier:
    build: ./dossier
    container_name: dossier
    restart: always
    ports:
      - "8086:8086"
    depends_on:
      - kafka1

  deal:
    build: ./deal
    container_name: deal
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka1

  gateway:
    build: ./gateway
    container_name: gateway
    restart: always
    ports:
      - "8089:8089"


