version: "3.9"
services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8089:8089"
    depends_on:
      - postgres1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres1:5433/gateway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "deal"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  postgres1:
    image: postgres:13.3
    environment:
      DATABASE_URL: "jdbc:postgresql://localhost:5433/postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    expose:
        - "5433"
    ports:
      - "5433:5433"


  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "finish-registration,create-documents,send-documents,send-ses,credit-issued,application-denied"

