feign:
   deal:
    url: http://localhost:8081/deal
   application:
     url: http://localhost:8082/application
server:
  port: 8089
jwt:
#  header: Authorization
  secret: CHANGE_ME
#  expiration: 604800
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    driver-class-name: org.postgresql.Driver
    user: postgres
    password: password
    url: jdbc:postgresql://localhost:5433/postgres



